---
- name: Create new user
  hosts: all
  become: yes  # This allows the tasks to be run with root privileges

  tasks:
    - name: Create a new user
      user:
        name: ravi
        state: present  # Ensure the user exists
        shell: /bin/bash  # Specify the user's shell
        createhome: yes  # Create user's home directory
