---
- name: Install Maven
  hosts: all
  become: true
  tasks:
    - name: Run a Shell Command
      ansible.builtin.shell:
        cmd: "sudo apt install maven"
        responses:
          ".*": "yes"
      register: command_output

    - name: Print Command Output
      ansible.builtin.debug:
        var: command_output.stdout_lines

