---
- name: Install Nginx
  hosts: all
  become: yes  # This allows the tasks to be run with root privileges
  tasks:
    - name: Install Nginx package
      package:
        name: nginx  # Package name for Nginx
        state: present  # Ensure Nginx is present, change to 'latest' for the latest version

    - name: Start Nginx service
      service:
        name: nginx  # Service name for Nginx
        state: started  # Ensure the service is started
        enabled: yes  # Ensure the service starts on boot
